name: nightly-builds
on:
  push:
    branches: [master]

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        conf: [Release]
    env:
      BUILD_TYPE: ${{ matrix.conf }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create build environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{github.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake $GITHUB_WORKSPACE -G "Visual Studio 16 2019" -T v141_xp -A win32

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --config $BUILD_TYPE

      - name: Prepare artifacts
        run: |
          mkdir publish\
          move build\bin\${{env.BUILD_TYPE}}\gsm-library.dll publish\gsm-library.dll
          move build\bin\${{env.BUILD_TYPE}}\gsm-loader.exe publish\gsm-loader.exe
          move resources\program_dir\*.* publish\

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: |
            publish/*

  release:
    name: release-builds
    runs-on: ubuntu-latest
    needs: [build-windows]
    steps:
      - name: Fetch artifacts
        uses: actions/download-artifact@v2

      - name: Repackage binaries
        run: |
          cd Windows
          zip -r ../goldsrc-monitor-win32.zip *

      - name: Remove old release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: continious
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload new release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: goldsrc-monitor*
          tag: continious
          overwrite: true
          prerelease: true
          release_name: GoldSrc Monitor Continuous Build
